
worker_processes  1;


events {
    worker_connections  1024;
}


http {

	upstream backend {
        server web-red;
        server web-blue;
        server web-green;
    }

    server {

        location / {
            proxy_pass http://backend;
        }
    }
}